consolidate and simplify images (#14)
* consolidate and simplify images
* update: fix syntax errors
* update: lots of cleanup
* update: move heavy stuff to patch
* update: break everything
* update: all the things
* update: version 4.0.2
* add: gh actions

diff --git a/container/base/Dockerfile.codercom b/container/base/Dockerfile.codercom
--- a/container/base/Dockerfile.codercom
+++ b/container/base/Dockerfile.codercom
@@ -1,57 +1,19 @@
-FROM codercom/code-server:3.12.0
+FROM docker.io/codercom/code-server:4.0.2
 
-### Atomic/OpenShift Labels - https://github.com/projectatomic/ContainerApplicationGenericLabels
+### https://github.com/opencontainers/image-spec/blob/main/annotations.md
 LABEL name="custom-code-server" \
       maintainer="koree@redhat.com" \
-      vendor="Coder" \
-      version="3.12.0" \
+      version="4.0.2" \
       summary="Custom Code Server" \
-      description="Custom Code Server base image with a basic collection of tools"
+      org.opencontainers.image.description.vendor="codercom" \
+      org.opencontainers.image.description="Custom Code Server base image with a basic collection of tools" \
+      org.opencontainers.image.source="https://github.com/codekow/code-server"
+
+ARG CODE_SERVER_VERSION
 
 # bug: hadolint doesn't see user below
 # hadolint ignore=DL3002
 USER root
-
-# Set shell for RUN commands to ensure consistent execution
-SHELL ["/bin/bash", "-o", "pipefail", "-c"]
-
-# fix: node CA trust defaults for requests / node
-ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
-#ENV NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
-
-# fix: path for local bin
-ENV PATH=$PATH:/home/coder/.local/bin
-
-# setup: basic home files
-COPY skel /etc/skel
-
-# setup: entrypoint and other scripts over 
-COPY bin /usr/local/bin
-
-# non interactive install
-ENV DEBIAN_FRONTEND=noninteractive
-
-# install: updates, utils, and python
-# hadolint ignore=DL3008 
-RUN apt-get update && \
-    apt-get -y install --no-install-recommends \
-    libnss-wrapper \
-    apt-transport-https lsb-release \
-    curl gnupg wget \
-    dnsutils traceroute \
-    git gcc g++ cmake make \
-    python3 python3-pip python3-venv python3-dev \
-    libcurl4-openssl-dev libssl-dev pkg-config \
-    bash-completion pass rsync tree zsh zip unzip \
-    krb5-user libkrb5-dev \
-    tmux screen \
-    nano vim jq && \
-    rm -rf /var/lib/apt/lists/* && \
-    chmod g+w /etc/passwd
-
-# fix: alias python / pip 
-RUN ln -s /usr/bin/python3 /usr/local/bin/python && \
-    ln -s /usr/bin/pip3 /usr/local/bin/pip
 
 # install: oc
 ENV OC3_VERSION="3.11.374"
@@ -79,18 +41,21 @@ RUN curl -sL "${OC3_URL}" -o oc.tgz && \
     rm oc.tgz && \
     ln -s /usr/local/bin/oc-wrapper.sh /usr/local/bin/oc
 
-# expose ports for local app / s2i
+# install: entrypoint and other scripts
+COPY bin /usr/local/bin
+
+# expose: ports for local app / s2i
 EXPOSE 1337 8000 8050 8080
 
-WORKDIR /home/coder
 USER coder
 
+WORKDIR /home/coder
 VOLUME /home/coder
 
-HEALTHCHECK --interval=30s \
-            --timeout=60s \
-            --retries=3 \
-  CMD curl -sf http://127.0.0.1:1337 || exit 1
+# HEALTHCHECK --interval=30s \
+#             --timeout=60s \
+#             --retries=3 \
+#   CMD curl -sf http://127.0.0.1:1337 || exit 1
 
 ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
 CMD ["dumb-init", "fixuid", "-q", "code-server", "--bind-addr", "0.0.0.0:1337", ".", "--disable-telemetry"]
diff --git a/container/base/Dockerfile.ubi8 b/container/base/Dockerfile.ubi8
--- a/container/base/Dockerfile.ubi8
+++ b/container/base/Dockerfile.ubi8
@@ -1,55 +1,27 @@
-FROM registry.access.redhat.com/ubi8/ubi
+FROM registry.access.redhat.com/ubi8/ubi:8.5
 
-### Atomic/OpenShift Labels - https://github.com/projectatomic/ContainerApplicationGenericLabels
+### https://github.com/opencontainers/image-spec/blob/main/annotations.md
 LABEL name="custom-code-server" \
       maintainer="koree@redhat.com" \
-      vendor="Coder" \
-      version="3.12.0" \
+      version="4.0.2" \
       summary="Custom Code Server" \
-      description="Custom Code Server base image with a basic collection of tools"
+      org.opencontainers.image.description.vendor="codercom" \
+      org.opencontainers.image.description="Custom Code Server base image with a basic collection of tools" \
+      org.opencontainers.image.source="https://github.com/codekow/code-server"
+
+ARG CODE_SERVER_VERSION
 
 # bug: hadolint doesn't see user below
 # hadolint ignore=DL3002
 USER root
 
-# Set shell for RUN commands to ensure consistent execution
-SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+# setup: coder user
+RUN useradd coder -u 1000 -g 0 && \
+    chmod 700 /home/coder && \
+    chown -R 1000:0 /home/coder
 
-# fix: node CA trust defaults for requests / node
-ENV REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt
-#ENV NODE_EXTRA_CA_CERTS=/etc/pki/tls/certs/ca-bundle.crt
-
-# fix: path for local bin
-ENV PATH=$PATH:/home/coder/.local/bin
-
-WORKDIR /home/coder
-
-# setup: basic home files
-COPY skel /etc/skel
-
-# setup: entrypoint and other scripts over 
-COPY bin /usr/local/bin
-
-ARG CODE_SERVER_VERSION
-
-RUN rpm -ivh https://github.com/cdr/code-server/releases/download/v${CODE_SERVER_VERSION:-3.12.0}/code-server-${CODE_SERVER_VERSION:-3.12.0}-amd64.rpm && \
-    dnf update -y && \
-    dnf install -y \
-    nss_wrapper \
-    curl gnupg wget \
-    bind-utils \
-    git gcc gcc-c++ cmake make \
-    python3 python3-pip \
-    pkg-config \
-    bash-completion rsync zip unzip \
-    krb5-workstation \
-    nano vim jq && \
-    dnf clean all && \
-    chmod g+w /etc/passwd
-
-# fix: alias python / pip 
-RUN ln -s /usr/bin/python3 /usr/local/bin/python && \
-    ln -s /usr/bin/pip3 /usr/local/bin/pip
+# install: code-server
+RUN rpm -ivh https://github.com/cdr/code-server/releases/download/v${CODE_SERVER_VERSION:-4.0.2}/code-server-${CODE_SERVER_VERSION:-4.0.2}-amd64.rpm
 
 # install: oc
 ENV OC3_VERSION="3.11.374"
@@ -77,13 +49,21 @@ RUN curl -sL "${OC3_URL}" -o oc.tgz && \
     rm oc.tgz && \
     ln -s /usr/local/bin/oc-wrapper.sh /usr/local/bin/oc
 
-# expose ports for local app / s2i
+# install: entrypoint and other scripts
+COPY bin /usr/local/bin
+
+# expose: ports for local app / s2i
 EXPOSE 1337 8000 8050 8080
 
-WORKDIR /home/coder
-USER 1001
+USER coder
 
+WORKDIR /home/coder
 VOLUME /home/coder
+
+# HEALTHCHECK --interval=30s \
+#             --timeout=60s \
+#             --retries=3 \
+#   CMD curl -sf http://127.0.0.1:1337 || exit 1
 
 ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
 CMD ["code-server", "--bind-addr", "0.0.0.0:1337", ".", "--disable-telemetry"]
